import pytest

from durable_workflow import serializer
from durable_workflow.errors import AvroNotInstalledError

try:
    import avro  # type: ignore[import-not-found]  # noqa: F401

    _AVRO_AVAILABLE = True
except ImportError:
    _AVRO_AVAILABLE = False

requires_avro = pytest.mark.skipif(
    not _AVRO_AVAILABLE, reason="avro extra not installed"
)


class TestEncode:
    def test_list(self) -> None:
        assert serializer.encode(["a", 1, True]) == '["a",1,true]'

    def test_dict(self) -> None:
        assert serializer.encode({"k": "v"}) == '{"k":"v"}'

    def test_none(self) -> None:
        assert serializer.encode(None) == "null"


class TestDecode:
    def test_roundtrip_list(self) -> None:
        assert serializer.decode(serializer.encode(["a", 1, True])) == ["a", 1, True]

    def test_none_blob(self) -> None:
        assert serializer.decode(None) is None

    def test_empty_string(self) -> None:
        assert serializer.decode("") is None

    def test_valid_json(self) -> None:
        assert serializer.decode('{"x":1}') == {"x": 1}

    def test_json_codec_explicit(self) -> None:
        assert serializer.decode('"hello"', codec="json") == "hello"

    def test_non_json_codec_raises(self) -> None:
        with pytest.raises(ValueError, match="Cannot decode payload with codec"):
            serializer.decode("blob", codec="workflow-serializer-y")

    def test_invalid_json_raises(self) -> None:
        with pytest.raises(ValueError, match="not valid JSON"):
            serializer.decode("not-json")

    def test_invalid_json_with_json_codec_raises(self) -> None:
        with pytest.raises(ValueError, match="not valid JSON"):
            serializer.decode("not-json", codec="json")


class TestDecodeEnvelope:
    def test_unwraps_codec_blob_dict(self) -> None:
        assert serializer.decode_envelope({"codec": "json", "blob": '["a",1]'}) == ["a", 1]

    def test_falls_back_to_raw_string(self) -> None:
        assert serializer.decode_envelope('["a",1]') == ["a", 1]

    def test_falls_back_with_codec(self) -> None:
        assert serializer.decode_envelope('"hello"', codec="json") == "hello"

    def test_rejects_unknown_envelope_codec(self) -> None:
        with pytest.raises(ValueError, match="Cannot decode payload with codec"):
            serializer.decode_envelope({"codec": "workflow-serializer-y", "blob": "data"})

    def test_none_passthrough(self) -> None:
        assert serializer.decode_envelope(None) is None

    def test_empty_string_passthrough(self) -> None:
        assert serializer.decode_envelope("") is None


class TestEnvelope:
    def test_structure(self) -> None:
        env = serializer.envelope(["a", 1])
        assert env["codec"] == "json"
        assert env["blob"] == '["a",1]'

    def test_none_value(self) -> None:
        env = serializer.envelope(None)
        assert env == {"codec": "json", "blob": "null"}


# Fixture blobs were generated by the PHP workflow package's
# Workflow\Serializers\Avro::serialize() so these tests double as a
# cross-language wire-format contract against the PHP producer.
_PHP_AVRO_FIXTURES: dict[str, tuple[str, object]] = {
    "null": ("AAhudWxsAg==", None),
    "bool_true": ("AAh0cnVlAg==", True),
    "int_42": ("AAQ0MgI=", 42),
    "float": ("AAgzLjE0Ag==", 3.14),
    "string": ("AA4iaGVsbG8iAg==", "hello"),
    "list": ("AA5bMSwyLDNdAg==", [1, 2, 3]),
    "map": ("AC57ImEiOjEsImIiOnsiYyI6WzQsNV19fQI=", {"a": 1, "b": {"c": [4, 5]}}),
    "nested": (
        "AIQBeyJvcmRlcl9pZCI6Im9yZC03IiwiYW1vdW50Ijo5OS41LCJpdGVtcyI6W3sic2t1IjoiQUJDIiwicXR5IjoyfV19Ag==",
        {"order_id": "ord-7", "amount": 99.5, "items": [{"sku": "ABC", "qty": 2}]},
    ),
}


@requires_avro
class TestAvroCodec:
    def test_round_trip_primitives(self) -> None:
        for value in (None, True, False, 0, -1, 42, 3.14, "hello"):
            blob = serializer.encode(value, codec="avro")
            assert serializer.decode(blob, codec="avro") == value

    def test_round_trip_containers(self) -> None:
        for value in ([], [1, 2, 3], {}, {"a": 1, "b": [2, 3]}, [{"k": "v"}]):
            blob = serializer.encode(value, codec="avro")
            assert serializer.decode(blob, codec="avro") == value

    @pytest.mark.parametrize(
        "name,blob,expected",
        [(name, blob, expected) for name, (blob, expected) in _PHP_AVRO_FIXTURES.items()],
    )
    def test_decodes_php_produced_blobs(self, name: str, blob: str, expected: object) -> None:
        assert serializer.decode(blob, codec="avro") == expected

    def test_envelope_structure(self) -> None:
        env = serializer.envelope([1, 2], codec="avro")
        assert env["codec"] == "avro"
        assert env["blob"] == serializer.encode([1, 2], codec="avro")

    def test_decode_envelope_routes_by_inner_codec(self) -> None:
        env = serializer.envelope({"x": 1}, codec="avro")
        assert serializer.decode_envelope(env) == {"x": 1}

    def test_decode_envelope_preserves_json_over_codec_arg(self) -> None:
        # Envelope codec wins even when caller passes a different `codec`.
        env = serializer.envelope([9, 10], codec="avro")
        assert serializer.decode_envelope(env, codec="json") == [9, 10]

    def test_typed_schema_prefix_rejected(self) -> None:
        # 0x01-prefixed payloads would need a writer schema the SDK doesn't
        # currently carry; the error must be loud and actionable, not a
        # silent mis-decode.
        import base64

        typed_blob = base64.b64encode(b"\x01deadbeef").decode()
        with pytest.raises(ValueError, match="Typed Avro payload"):
            serializer.decode(typed_blob, codec="avro")

    def test_unknown_prefix_rejected(self) -> None:
        import base64

        weird_blob = base64.b64encode(b"\x07garbage").decode()
        with pytest.raises(ValueError, match="Unknown Avro payload prefix"):
            serializer.decode(weird_blob, codec="avro")

    def test_json_tagged_avro_raises_diagnostic(self) -> None:
        # A JSON string wrongly tagged as `avro` produces a typed, actionable
        # error rather than a silent mis-decode.
        with pytest.raises(ValueError, match="look like JSON"):
            serializer.decode('{"x":1}', codec="avro")

    def test_empty_blob_is_none(self) -> None:
        assert serializer.decode("", codec="avro") is None
        assert serializer.decode(None, codec="avro") is None


class TestAvroNotInstalledError:
    """Verify AvroNotInstalledError is a proper ImportError subclass.

    This matters because callers who already catch ImportError to detect
    optional-dep absence (a common Python pattern) will transparently
    catch the SDK-specific error too.
    """

    def test_is_import_error_subclass(self) -> None:
        assert issubclass(AvroNotInstalledError, ImportError)

    def test_carries_install_hint_in_message(self) -> None:
        exc = AvroNotInstalledError("install with: pip install 'durable-workflow[avro]'")
        assert "durable-workflow[avro]" in str(exc)
