from __future__ import annotations

from tests.integration.polyglot_fixtures import PHP_HISTORY_EVENT_EXPECTED_KEYS

DOCUMENTED_HISTORY_EVENT_PAYLOAD_KEYS: dict[str, tuple[str, ...]] = {
    "StartAccepted": (
        "workflow_command_id",
        "workflow_instance_id",
        "workflow_run_id",
        "workflow_class",
        "workflow_type",
        "business_key",
        "visibility_labels",
        "memo",
        "search_attributes",
        "outcome",
        "rejection_reason",
    ),
    "StartRejected": (
        "workflow_command_id",
        "workflow_instance_id",
        "workflow_run_id",
        "workflow_class",
        "workflow_type",
        "business_key",
        "visibility_labels",
        "memo",
        "search_attributes",
        "outcome",
        "rejection_reason",
    ),
    "WorkflowStarted": (
        "workflow_class",
        "workflow_type",
        "workflow_instance_id",
        "workflow_run_id",
        "workflow_command_id",
        "business_key",
        "visibility_labels",
        "memo",
        "search_attributes",
        "execution_timeout_seconds",
        "run_timeout_seconds",
        "execution_deadline_at",
        "run_deadline_at",
        "workflow_definition_fingerprint",
        "declared_queries",
        "declared_query_contracts",
        "declared_signals",
        "declared_signal_contracts",
        "declared_updates",
        "declared_update_contracts",
        "declared_entry_method",
        "declared_entry_mode",
        "declared_entry_declaring_class",
    ),
    "WorkflowContinuedAsNew": (
        "sequence",
        "continued_to_run_id",
        "continued_to_run_number",
        "workflow_link_id",
        "closed_reason",
    ),
    "ActivityScheduled": (
        "activity_execution_id",
        "activity_class",
        "activity_type",
        "sequence",
        "activity",
    ),
    "ActivityStarted": (
        "activity_execution_id",
        "activity_attempt_id",
        "activity_class",
        "activity_type",
        "sequence",
        "attempt_number",
        "activity",
        "parallel_group_path",
    ),
    "ActivityHeartbeatRecorded": (
        "activity_execution_id",
        "activity_attempt_id",
        "activity_class",
        "activity_type",
        "sequence",
        "attempt_number",
        "heartbeat_at",
        "lease_expires_at",
        "activity",
        "activity_attempt",
        "progress",
    ),
    "ActivityRetryScheduled": (
        "activity_execution_id",
        "activity_attempt_id",
        "activity_class",
        "activity_type",
        "sequence",
        "retry_task_id",
        "retry_of_task_id",
        "retry_available_at",
        "retry_backoff_seconds",
        "retry_after_attempt_id",
        "retry_after_attempt",
        "max_attempts",
        "retry_policy",
        "timeout_kind",
        "exception_type",
        "exception_class",
        "message",
        "code",
        "exception",
        "activity",
        "parallel_group_path",
    ),
    "ActivityCompleted": (
        "activity_execution_id",
        "activity_attempt_id",
        "activity_class",
        "activity_type",
        "sequence",
        "attempt_number",
        "result",
        "payload_codec",
        "activity",
        "parallel_group_path",
    ),
    "ActivityFailed": (
        "activity_execution_id",
        "activity_attempt_id",
        "activity_class",
        "activity_type",
        "sequence",
        "attempt_number",
        "failure_id",
        "failure_category",
        "non_retryable",
        "exception_type",
        "exception_class",
        "message",
        "code",
        "exception",
        "activity",
        "parallel_group_path",
        "structural_limit_kind",
        "structural_limit_value",
        "structural_limit_configured",
    ),
    "ActivityCancelled": (
        "workflow_command_id",
        "activity_execution_id",
        "activity_attempt_id",
        "activity_class",
        "activity_type",
        "sequence",
        "attempt_number",
        "cancelled_at",
        "activity",
        "activity_attempt",
    ),
    "ActivityTimedOut": (
        "activity_execution_id",
        "activity_attempt_id",
        "activity_class",
        "activity_type",
        "sequence",
        "attempt_number",
        "failure_id",
        "failure_category",
        "timeout_kind",
        "message",
        "exception_class",
        "schedule_deadline_at",
        "close_deadline_at",
        "schedule_to_close_deadline_at",
        "heartbeat_deadline_at",
        "activity",
        "parallel_group_path",
    ),
    "TimerScheduled": (
        "timer_id",
        "sequence",
        "delay_seconds",
        "fire_at",
        "timer_kind",
        "condition_wait_id",
        "condition_key",
        "condition_definition_fingerprint",
        "signal_wait_id",
        "signal_name",
    ),
    "TimerFired": (
        "timer_id",
        "sequence",
        "delay_seconds",
        "fired_at",
        "timer_kind",
        "condition_wait_id",
        "condition_key",
        "condition_definition_fingerprint",
        "signal_wait_id",
        "signal_name",
    ),
    "TimerCancelled": (
        "timer_id",
        "sequence",
        "delay_seconds",
        "fire_at",
        "timer_kind",
        "condition_wait_id",
        "condition_key",
        "condition_definition_fingerprint",
        "signal_wait_id",
        "signal_name",
        "cancelled_at",
    ),
    "SignalReceived": (
        "workflow_command_id",
        "signal_id",
        "workflow_instance_id",
        "workflow_run_id",
        "signal_name",
        "signal_wait_id",
    ),
    "SignalApplied": (
        "workflow_command_id",
        "signal_id",
        "signal_name",
        "signal_wait_id",
        "sequence",
        "value",
    ),
    "SignalWaitOpened": (
        "signal_name",
        "signal_wait_id",
        "sequence",
        "timeout_seconds",
    ),
    "UpdateAccepted": (
        "workflow_command_id",
        "update_id",
        "workflow_instance_id",
        "workflow_run_id",
        "update_name",
        "arguments",
    ),
    "UpdateRejected": (
        "workflow_command_id",
        "update_id",
        "workflow_instance_id",
        "workflow_run_id",
        "update_name",
        "arguments",
        "validation_errors",
    ),
    "UpdateApplied": (
        "workflow_command_id",
        "update_id",
        "workflow_instance_id",
        "workflow_run_id",
        "update_name",
        "arguments",
        "sequence",
    ),
    "UpdateCompleted": (
        "workflow_command_id",
        "update_id",
        "workflow_instance_id",
        "workflow_run_id",
        "update_name",
        "sequence",
        "result",
        "failure_id",
        "failure_category",
        "non_retryable",
        "exception_type",
        "exception_class",
        "message",
        "code",
        "exception",
    ),
    "ConditionWaitOpened": (
        "condition_wait_id",
        "condition_key",
        "condition_definition_fingerprint",
        "sequence",
        "timeout_seconds",
    ),
    "ConditionWaitSatisfied": (
        "condition_wait_id",
        "condition_key",
        "condition_definition_fingerprint",
        "sequence",
        "timer_id",
        "timeout_seconds",
    ),
    "ConditionWaitTimedOut": (
        "condition_wait_id",
        "condition_key",
        "condition_definition_fingerprint",
        "sequence",
        "timer_id",
        "timeout_seconds",
    ),
    "SideEffectRecorded": (
        "sequence",
        "result",
    ),
    "VersionMarkerRecorded": (
        "sequence",
        "change_id",
        "version",
        "min_supported",
        "max_supported",
    ),
    "ChildWorkflowScheduled": (
        "sequence",
        "workflow_link_id",
        "child_call_id",
        "child_workflow_instance_id",
        "child_workflow_run_id",
        "child_workflow_class",
        "child_workflow_type",
        "parent_close_policy",
        "retry_policy",
        "timeout_policy",
    ),
    "ChildRunStarted": (
        "sequence",
        "workflow_link_id",
        "child_call_id",
        "child_workflow_instance_id",
        "child_workflow_run_id",
        "child_workflow_class",
        "child_workflow_type",
        "child_run_number",
        "retry_policy",
        "timeout_policy",
        "execution_timeout_seconds",
        "run_timeout_seconds",
        "execution_deadline_at",
        "run_deadline_at",
    ),
    "ChildRunCompleted": (
        "sequence",
        "workflow_link_id",
        "child_call_id",
        "child_workflow_instance_id",
        "child_workflow_run_id",
        "child_workflow_class",
        "child_workflow_type",
        "child_run_number",
        "child_status",
        "closed_reason",
        "closed_at",
        "output",
        "parallel_group_path",
    ),
    "ChildRunFailed": (
        "sequence",
        "workflow_link_id",
        "child_call_id",
        "child_workflow_instance_id",
        "child_workflow_run_id",
        "child_workflow_class",
        "child_workflow_type",
        "child_run_number",
        "child_status",
        "closed_reason",
        "closed_at",
        "failure_id",
        "failure_category",
        "exception_type",
        "exception_class",
        "message",
        "exception",
        "parallel_group_path",
    ),
    "ChildRunCancelled": (
        "sequence",
        "workflow_link_id",
        "child_call_id",
        "child_workflow_instance_id",
        "child_workflow_run_id",
        "child_workflow_class",
        "child_workflow_type",
        "child_run_number",
        "child_status",
        "closed_reason",
        "closed_at",
        "parallel_group_path",
    ),
    "ChildRunTerminated": (
        "sequence",
        "workflow_link_id",
        "child_call_id",
        "child_workflow_instance_id",
        "child_workflow_run_id",
        "child_workflow_class",
        "child_workflow_type",
        "child_run_number",
        "child_status",
        "closed_reason",
        "closed_at",
        "parallel_group_path",
    ),
    "SearchAttributesUpserted": (
        "sequence",
        "attributes",
        "merged",
    ),
    "MemoUpserted": (
        "sequence",
        "entries",
        "merged",
    ),
    "RepairRequested": (
        "workflow_command_id",
        "workflow_instance_id",
        "workflow_run_id",
        "command_type",
        "outcome",
        "liveness_state",
        "wait_kind",
        "task_id",
        "task_type",
    ),
    "CancelRequested": (
        "workflow_command_id",
        "workflow_instance_id",
        "workflow_run_id",
        "command_type",
        "reason",
    ),
    "WorkflowCancelled": (
        "workflow_command_id",
        "workflow_instance_id",
        "workflow_run_id",
        "failure_id",
        "failure_category",
        "closed_reason",
        "exception_class",
        "message",
        "reason",
    ),
    "TerminateRequested": (
        "workflow_command_id",
        "workflow_instance_id",
        "workflow_run_id",
        "command_type",
        "reason",
    ),
    "WorkflowTerminated": (
        "workflow_command_id",
        "workflow_instance_id",
        "workflow_run_id",
        "failure_id",
        "failure_category",
        "closed_reason",
        "exception_class",
        "message",
        "reason",
    ),
    "ArchiveRequested": (
        "workflow_command_id",
        "workflow_instance_id",
        "workflow_run_id",
        "command_type",
        "outcome",
        "reason",
    ),
    "WorkflowArchived": (
        "workflow_command_id",
        "workflow_instance_id",
        "workflow_run_id",
        "archive_command_id",
        "reason",
    ),
    "WorkflowTimedOut": (
        "failure_id",
        "timeout_kind",
        "failure_category",
        "message",
        "exception_class",
        "execution_deadline_at",
        "run_deadline_at",
    ),
    "WorkflowCompleted": ("output",),
    "WorkflowFailed": (
        "failure_id",
        "source_kind",
        "source_id",
        "failure_category",
        "non_retryable",
        "exception_type",
        "exception_class",
        "message",
        "exception",
        "structural_limit_kind",
        "structural_limit_value",
        "structural_limit_configured",
    ),
    "FailureHandled": (
        "failure_id",
        "sequence",
        "failure_category",
        "source_kind",
        "source_id",
        "propagation_kind",
        "exception_class",
        "exception_type",
        "message",
        "handled",
    ),
    "ParentClosePolicyApplied": (
        "child_instance_id",
        "child_run_id",
        "policy",
        "reason",
    ),
    "ParentClosePolicyFailed": (
        "child_instance_id",
        "child_run_id",
        "policy",
        "reason",
        "error",
    ),
    "MessageCursorAdvanced": (
        "stream_key",
        "previous_position",
        "new_position",
    ),
    "ScheduleCreated": (
        "spec",
        "action",
        "overlap_policy",
        "next_fire_at",
        "command_context",
    ),
    "SchedulePaused": (
        "reason",
        "paused_at",
        "command_context",
    ),
    "ScheduleResumed": (
        "next_fire_at",
        "command_context",
    ),
    "ScheduleUpdated": (
        "changed_fields",
        "spec",
        "action",
        "overlap_policy",
        "next_fire_at",
        "command_context",
    ),
    "ScheduleTriggered": (
        "workflow_instance_id",
        "workflow_run_id",
        "schedule_id",
        "schedule_ulid",
        "cron_expression",
        "timezone",
        "overlap_policy",
        "outcome",
        "effective_overlap_policy",
        "trigger_number",
        "occurrence_time",
        "command_context",
    ),
    "ScheduleDeleted": (
        "reason",
        "deleted_at",
        "command_context",
    ),
    "ScheduleTriggerSkipped": (
        "reason",
        "skipped_trigger_count",
        "last_skipped_at",
        "command_context",
    ),
}


SDK_INTERPRETED_HISTORY_EVENTS = frozenset(
    {
        "WorkflowStarted",
        "ActivityCompleted",
        "TimerFired",
        "SignalReceived",
        "UpdateAccepted",
        "UpdateApplied",
        "ConditionWaitOpened",
        "ConditionWaitSatisfied",
        "ConditionWaitTimedOut",
        "SideEffectRecorded",
        "VersionMarkerRecorded",
        "ChildRunCompleted",
        "ChildRunFailed",
        "SearchAttributesUpserted",
    }
)

SDK_PRESERVED_ONLY_HISTORY_EVENTS = frozenset(DOCUMENTED_HISTORY_EVENT_PAYLOAD_KEYS) - SDK_INTERPRETED_HISTORY_EVENTS

SDK_TOLERATED_FIXTURE_EXTRA_KEYS = {
    "SignalReceived": frozenset({"arguments", "payload_codec"}),
    "UpdateApplied": frozenset({"payload_codec"}),
    "SideEffectRecorded": frozenset({"payload_codec"}),
    "ChildRunCompleted": frozenset({"result", "payload_codec"}),
}


def test_every_documented_history_event_has_an_sdk_classification() -> None:
    assert SDK_INTERPRETED_HISTORY_EVENTS
    assert SDK_PRESERVED_ONLY_HISTORY_EVENTS
    assert SDK_INTERPRETED_HISTORY_EVENTS.isdisjoint(SDK_PRESERVED_ONLY_HISTORY_EVENTS)
    assert set(
        DOCUMENTED_HISTORY_EVENT_PAYLOAD_KEYS
    ) == SDK_INTERPRETED_HISTORY_EVENTS | SDK_PRESERVED_ONLY_HISTORY_EVENTS


def test_php_history_fixture_key_expectations_match_documented_contract() -> None:
    for event_type, fixture_keys in PHP_HISTORY_EVENT_EXPECTED_KEYS.items():
        documented_keys = set(DOCUMENTED_HISTORY_EVENT_PAYLOAD_KEYS[event_type])
        expected_keys = set(fixture_keys)
        tolerated_extra_keys = set(SDK_TOLERATED_FIXTURE_EXTRA_KEYS.get(event_type, frozenset()))

        assert expected_keys - documented_keys == tolerated_extra_keys, event_type
        assert documented_keys - expected_keys == set(), event_type
