from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _pkg_version

try:
    __version__ = _pkg_version("durable-workflow")
except PackageNotFoundError:  # source checkout without installed metadata
    __version__ = "0.0.0+unknown"

from . import activity, sync, testing, workflow
from .activity import ActivityContext, ActivityInfo
from .auth_composition import (
    AUTH_COMPOSITION_CONTRACT_SCHEMA,
    AUTH_COMPOSITION_CONTRACT_VERSION,
    AUTH_COMPOSITION_REQUIRED_EFFECTIVE_CONFIG_FIELDS,
    AuthCompositionContract,
    AuthCompositionContractError,
    parse_auth_composition_contract,
)
from .client import (
    Client,
    ScheduleAction,
    ScheduleBackfillResult,
    ScheduleDescription,
    ScheduleHandle,
    ScheduleList,
    ScheduleSpec,
    ScheduleTriggerResult,
    TaskQueueAdmission,
    TaskQueueDescription,
    TaskQueueList,
    TaskQueueQueryAdmission,
    TaskQueueTaskAdmission,
    WorkflowExecution,
    WorkflowHandle,
    WorkflowList,
)
from .errors import (
    ActivityCancelled,
    ChildWorkflowFailed,
    DurableWorkflowError,
    InvalidArgument,
    NamespaceNotFound,
    NonRetryableError,
    QueryFailed,
    ScheduleAlreadyExists,
    ScheduleNotFound,
    ServerError,
    Unauthorized,
    UpdateRejected,
    WorkflowAlreadyStarted,
    WorkflowCancelled,
    WorkflowFailed,
    WorkflowNotFound,
    WorkflowPayloadDecodeError,
    WorkflowTerminated,
)
from .external_storage import (
    EXTERNAL_PAYLOAD_REFERENCE_SCHEMA,
    ExternalPayloadIntegrityError,
    ExternalPayloadReference,
    ExternalStorageDriver,
    LocalFilesystemExternalStorage,
)
from .external_task_input import (
    EXTERNAL_TASK_INPUT_CONTRACT_SCHEMA,
    EXTERNAL_TASK_INPUT_MEDIA_TYPE,
    EXTERNAL_TASK_INPUT_SCHEMA,
    EXTERNAL_TASK_INPUT_VERSION,
    ExternalTaskInput,
    ExternalTaskInputError,
    ExternalTaskInputIdentity,
    ExternalTaskLease,
    ExternalTaskWorkflowContext,
    parse_external_task_input,
    parse_external_task_input_artifact,
)
from .external_task_result import (
    EXTERNAL_TASK_RESULT_CONTRACT_SCHEMA,
    EXTERNAL_TASK_RESULT_MEDIA_TYPE,
    EXTERNAL_TASK_RESULT_SCHEMA,
    EXTERNAL_TASK_RESULT_VERSION,
    ExternalTaskFailure,
    ExternalTaskIdentity,
    ExternalTaskResult,
    ExternalTaskResultError,
    parse_external_task_result,
    parse_external_task_result_artifact,
)
from .interceptors import (
    ActivityHandler,
    ActivityInterceptorContext,
    PassthroughWorkerInterceptor,
    QueryTaskHandler,
    QueryTaskInterceptorContext,
    WorkerInterceptor,
    WorkflowTaskHandler,
    WorkflowTaskInterceptorContext,
)
from .metrics import (
    InMemoryMetrics,
    MetricsRecorder,
    NoopMetrics,
    PrometheusMetrics,
)
from .retry_policy import RetryPolicy, TransportRetryPolicy
from .serializer import (
    PayloadSizeWarningConfig,
    PayloadSizeWarningContext,
    external_storage_envelope,
    to_avro_payload_value,
    to_avro_payload_values,
)
from .worker import Worker
from .workflow import (
    ActivityRetryPolicy,
    ChildWorkflowRetryPolicy,
    ContinueAsNew,
    Replayer,
    ReplayOutcome,
    StartChildWorkflow,
    replay,
)

__all__ = [
    "__version__",
    "ActivityCancelled",
    "ActivityContext",
    "ActivityHandler",
    "ActivityInfo",
    "ActivityInterceptorContext",
    "ActivityRetryPolicy",
    "ChildWorkflowRetryPolicy",
    "ChildWorkflowFailed",
    "Client",
    "ContinueAsNew",
    "AUTH_COMPOSITION_CONTRACT_SCHEMA",
    "AUTH_COMPOSITION_CONTRACT_VERSION",
    "AUTH_COMPOSITION_REQUIRED_EFFECTIVE_CONFIG_FIELDS",
    "AuthCompositionContract",
    "AuthCompositionContractError",
    "NonRetryableError",
    "ReplayOutcome",
    "Replayer",
    "ScheduleAction",
    "ScheduleAlreadyExists",
    "ScheduleBackfillResult",
    "ScheduleDescription",
    "ScheduleHandle",
    "ScheduleList",
    "ScheduleNotFound",
    "ScheduleSpec",
    "ScheduleTriggerResult",
    "StartChildWorkflow",
    "TaskQueueAdmission",
    "TaskQueueDescription",
    "TaskQueueList",
    "TaskQueueQueryAdmission",
    "TaskQueueTaskAdmission",
    "Worker",
    "WorkerInterceptor",
    "WorkflowExecution",
    "WorkflowTaskHandler",
    "WorkflowTaskInterceptorContext",
    "WorkflowHandle",
    "WorkflowList",
    "WorkflowPayloadDecodeError",
    "activity",
    "parse_auth_composition_contract",
    "sync",
    "testing",
    "workflow",
    "DurableWorkflowError",
    "EXTERNAL_PAYLOAD_REFERENCE_SCHEMA",
    "ExternalPayloadIntegrityError",
    "ExternalPayloadReference",
    "ExternalStorageDriver",
    "ExternalTaskInput",
    "ExternalTaskInputError",
    "ExternalTaskInputIdentity",
    "ExternalTaskLease",
    "ExternalTaskWorkflowContext",
    "EXTERNAL_TASK_RESULT_CONTRACT_SCHEMA",
    "EXTERNAL_TASK_RESULT_MEDIA_TYPE",
    "ExternalTaskFailure",
    "ExternalTaskIdentity",
    "ExternalTaskResult",
    "ExternalTaskResultError",
    "parse_external_task_result_artifact",
    "InvalidArgument",
    "InMemoryMetrics",
    "LocalFilesystemExternalStorage",
    "MetricsRecorder",
    "NamespaceNotFound",
    "NoopMetrics",
    "QueryFailed",
    "PrometheusMetrics",
    "PayloadSizeWarningConfig",
    "PayloadSizeWarningContext",
    "PassthroughWorkerInterceptor",
    "QueryTaskHandler",
    "QueryTaskInterceptorContext",
    "RetryPolicy",
    "ServerError",
    "TransportRetryPolicy",
    "Unauthorized",
    "UpdateRejected",
    "WorkflowAlreadyStarted",
    "WorkflowCancelled",
    "WorkflowFailed",
    "WorkflowNotFound",
    "WorkflowTerminated",
    "EXTERNAL_TASK_INPUT_CONTRACT_SCHEMA",
    "EXTERNAL_TASK_INPUT_MEDIA_TYPE",
    "EXTERNAL_TASK_INPUT_SCHEMA",
    "EXTERNAL_TASK_INPUT_VERSION",
    "EXTERNAL_TASK_RESULT_SCHEMA",
    "EXTERNAL_TASK_RESULT_VERSION",
    "external_storage_envelope",
    "parse_external_task_input",
    "parse_external_task_input_artifact",
    "parse_external_task_result",
    "to_avro_payload_value",
    "to_avro_payload_values",
    "replay",
]
